### ISSUE TITLE
Fails to build if rsmpi is also a dependency

### ISSUE THREAD

**Issue by mscroggs** [LIHPC-Computational-Geometry/scotch-rs#12]
If the examples are run with these dependencies:

```toml
[dependencies]
scotch = { version = "0.2" }
mpi = { version = "0.8" }
```

Then build fails with error `a `libclang` shared library is not loaded on this thread`.

This appears to be caused by the bindgen feature `runtime`. The build also fails with the dependencies:

```toml
[dependencies]
scotch = { version = "0.2" }
[build-dependencies]
bindgen = {version="0.71", default-features=false, features=["runtime"]}
```

This appears to be due to scotch-sys having the build dependency `bindgen = { version = "0.65", default-features = false }`, while mpi-sys has the build dependency `bindgen = "0.69"`. In bindgen, the `runtime` feature is a default feature.
